// Mirror of stack/common/include/common/events.h (M6.5 D5).
// Keep in sync: CI greps both files for event-name drift.
// Field contracts are documented on each constant.

export const ev = {
  // Process lifecycle
  PROCESS_START: 'PROCESS_START',
  PROCESS_EXIT: 'PROCESS_EXIT',
  HEARTBEAT: 'HEARTBEAT', // {c_rnti, registered} | {registered_ues}
  UE_CMD_HINT: 'UE_CMD_HINT',
  UE_STATUS: 'UE_STATUS', // {mac, rrc, nas, c_rnti, sib, app_rx}
  BS_STATUS: 'BS_STATUS', // {registered_ues}
  UE_DETACH_IGNORED: 'UE_DETACH_IGNORED',

  // PHY / transport
  PHY_CONFIG: 'PHY_CONFIG', // {n_fft, cp_len}
  PHY_BIND_FAIL: 'PHY_BIND_FAIL',
  PHY_UDP_READY: 'PHY_UDP_READY',

  // Core / air framing
  AIR_FRAME_DECODE_FAIL: 'AIR_FRAME_DECODE_FAIL',
  SYSINFO_DECODE_FAIL: 'SYSINFO_DECODE_FAIL',
  BS_SIB_BROADCAST_ON: 'BS_SIB_BROADCAST_ON',

  // MAC RACH
  MAC_STATE_CHANGE: 'MAC_STATE_CHANGE', // {layer, old_state, new_state}
  MAC_RACH_MSG1: 'MAC_RACH_MSG1',
  MAC_RACH_MSG2: 'MAC_RACH_MSG2',
  MAC_RACH_MSG2_RX: 'MAC_RACH_MSG2_RX',
  MAC_RACH_MSG3: 'MAC_RACH_MSG3',
  MAC_RACH_MSG4: 'MAC_RACH_MSG4',
  MAC_RACH_MSG4_RX: 'MAC_RACH_MSG4_RX',
  RACH_SUCCESS: 'RACH_SUCCESS',
  RA_SUCCESS: 'RA_SUCCESS',
  RACH_BACKOFF: 'RACH_BACKOFF',
  RACH_RAR_TIMEOUT: 'RACH_RAR_TIMEOUT',
  RACH_CR_TIMEOUT: 'RACH_CR_TIMEOUT',
  RACH_FAILED: 'RACH_FAILED',
  RACH_START_IGNORED: 'RACH_START_IGNORED',
  RAR_IGNORED: 'RAR_IGNORED',
  CR_IGNORED: 'CR_IGNORED',
  MSG3_UNKNOWN_RA_RNTI: 'MSG3_UNKNOWN_RA_RNTI',
  UE_RACH_TX_UNEXPECTED: 'UE_RACH_TX_UNEXPECTED',
  BS_RACH_TX_UNEXPECTED: 'BS_RACH_TX_UNEXPECTED',

  // RRC
  RRC_UE_STATE: 'RRC_UE_STATE', // {old, new}: IDLE | CONNECTING | CONNECTED
  RRC_MIB_RX: 'RRC_MIB_RX', // {sfn, bw}
  RRC_SIB1_RX: 'RRC_SIB1_RX', // {plmn, tac, cell_id}
  RRC_SETUP_REQUEST_TX: 'RRC_SETUP_REQUEST_TX',
  RRC_SETUP_TX: 'RRC_SETUP_TX',
  RRC_SETUP_RX: 'RRC_SETUP_RX',
  RRC_SETUP_COMPLETE_TX: 'RRC_SETUP_COMPLETE_TX',
  RRC_SETUP_COMPLETE_RX: 'RRC_SETUP_COMPLETE_RX',
  RRC_UE_CONNECTED: 'RRC_UE_CONNECTED',
  RRC_RELEASE_TX: 'RRC_RELEASE_TX',
  RRC_RELEASED: 'RRC_RELEASED',
  RRC_UE_RELEASED: 'RRC_UE_RELEASED',
  RRC_SETUP_IGNORED: 'RRC_SETUP_IGNORED',
  RRC_SETUP_RX_IGNORED: 'RRC_SETUP_RX_IGNORED',
  RRC_RELEASE_IGNORED: 'RRC_RELEASE_IGNORED',
  RRC_SETUP_COMPLETE_UNKNOWN: 'RRC_SETUP_COMPLETE_UNKNOWN',

  // NAS
  NAS_STATE_CHANGE: 'NAS_STATE_CHANGE', // {old, new}: DEREGISTERED | REGISTERING | REGISTERED
  NAS_ATTACH_REQUEST_TX: 'NAS_ATTACH_REQUEST_TX',
  NAS_ATTACH_ACCEPT_TX: 'NAS_ATTACH_ACCEPT_TX',
  NAS_ATTACH_ACCEPT_RX: 'NAS_ATTACH_ACCEPT_RX',
  NAS_ATTACH_REJECT_RX: 'NAS_ATTACH_REJECT_RX',
  NAS_DETACH_TX: 'NAS_DETACH_TX',
  NAS_DETACH_RX: 'NAS_DETACH_RX',
  NAS_DETACH_UNKNOWN: 'NAS_DETACH_UNKNOWN',
  NAS_ACCEPT_IGNORED: 'NAS_ACCEPT_IGNORED',
  NAS_ATTACH_REQ_IGNORED: 'NAS_ATTACH_REQ_IGNORED',
  NAS_DETACH_IGNORED: 'NAS_DETACH_IGNORED',

  // Attach orchestration
  UE_ATTACH_PENDING_SIB: 'UE_ATTACH_PENDING_SIB',
  UE_ATTACH_START: 'UE_ATTACH_START',
  ATTACH_RETRY: 'ATTACH_RETRY',
  ATTACH_ABORT: 'ATTACH_ABORT',
  UE_DETACH_DONE: 'UE_DETACH_DONE',

  // User plane
  APP_DATA_TX: 'APP_DATA_TX',
  APP_DATA_RX: 'APP_DATA_RX',
  APP_ECHO_TX: 'APP_ECHO_TX',
  APP_RTT: 'APP_RTT', // {seq, rtt_ms}
  APP_TX_NO_CONTEXT: 'APP_TX_NO_CONTEXT',

  // PDU inspector: fields {layer, direction, len, hex, brief}
  PDU_TRACE: 'PDU_TRACE',
} as const

export type EventName = (typeof ev)[keyof typeof ev]

/** Events rendered as UE->BS arrows in the MSC diagram. */
export const MSC_UPLINK: Partial<Record<EventName, string>> = {
  MAC_RACH_MSG1: 'MSG1: PRACH',
  MAC_RACH_MSG3: 'MSG3: RRC Req',
  RRC_SETUP_REQUEST_TX: 'RRC Setup Req',
  RRC_SETUP_COMPLETE_TX: 'RRC Setup Cmpl',
  NAS_ATTACH_REQUEST_TX: 'NAS Attach Req',
  NAS_DETACH_TX: 'NAS Detach',
  RRC_RELEASE_TX: 'RRC Release',
}

/** Events rendered as BS->UE arrows in the MSC diagram. */
export const MSC_DOWNLINK: Partial<Record<EventName, string>> = {
  MAC_RACH_MSG2: 'MSG2: RAR',
  MAC_RACH_MSG4: 'MSG4: CR',
  RRC_SETUP_TX: 'RRC Setup',
  NAS_ATTACH_ACCEPT_TX: 'NAS Attach Accept',
}

export default ev
